version: '3.8'

services:
  backend:
    build: ./backend    # Tìm vị trí Dockerfile của backend trong thư mục backend
    volumes:
      - ./backend:/app  # mount toàn bộ nội dung của folder backend vào trong container
      - /app/venv
    ports:
      - "3001:3001"
    environment:
      - PYTHONUNBUFFERED=1
    command: python manage.py runserver 0.0.0.0:3001
    networks:
      - default

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "export PATH=$$PATH:/app/node_modules/.bin && npm run dev"
    networks:
      - default

networks:
  default:
    driver: bridge

## docker-compose up -d: container vẫn chạy dù tắt temrinal
## docker-compose up: container sẽ stop
## docker-compose up --build: docker luôn build lại images khi chạy