import Head from 'next/head';
import { Footer } from '../components/Footer';
import { Header } from '../components/Header';
import { Post } from '../components/Post';
import { Sidebar } from '../components/Sidebar';
import { Main } from '../layouts/Main';

export default function Home() {
  return (
    <>
      <Head>
        <title>Khanh Phan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/icons/ubuntu-icon.svg" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha384-k6RqeWeci5ZR/Lv4MR0sA0FfDOMrKyRdU7mtKQFL99DEZ5kXik7h1WY6jUZZg72L" crossorigin="anonymous" />
      </Head>
      <Main>
        <Post />
      </Main>
    </>
  );
}
