import Head from 'next/head';
import { Footer } from '../components/Footer';
import { Header } from '../components/Header';
import { Post } from '../components/Post';
import { Sidebar } from '../components/Sidebar';
import { Main } from '../layouts/Main';

export default function Home() {
  return (
    <>
      <Head>
        <title>Khanh Phan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/icons/ubuntu-icon.svg" />
      </Head>
      <Main>
        <Post />
      </Main>
    </>
  );
}
