# Generated by Django 4.2.13 on 2024-06-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_categories_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='hex_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
