# Generated by Django 4.2.13 on 2024-06-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hex_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
